# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosineSimilarity <- function(X, Y) {
    .Call(`_Rcppist_cosineSimilarity`, X, Y)
}

csort <- function(X) {
    .Call(`_Rcppist_csort`, X)
}

ctanh <- function(X) {
    .Call(`_Rcppist_ctanh`, X)
}

l2lise <- function(X) {
    .Call(`_Rcppist_l2lise`, X)
}

rcpp_hello_world <- function() {
    .Call(`_Rcppist_rcpp_hello_world`)
}

rcpp_zlise <- function(X) {
    .Call(`_Rcppist_rcpp_zlise`, X)
}

relu <- function(X) {
    .Call(`_Rcppist_relu`, X)
}

softmax <- function(X) {
    .Call(`_Rcppist_softmax`, X)
}

zlise <- function(X) {
    .Call(`_Rcppist_zlise`, X)
}

